# Generated by Django 4.2.2 on 2023-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="eight",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="five",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="four",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="nine",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="one",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="seven",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="six",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="three",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="two",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
