# Generated by Django 4.2.2 on 2023-07-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_game_eight_game_five_game_four_game_nine_game_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="eight",
            field=models.CharField(default="start", max_length=225),
        ),
        migrations.AlterField(
            model_name="game",
            name="five",
            field=models.CharField(default="start", max_length=225),
        ),
        migrations.AlterField(
            model_name="game",
            name="four",
            field=models.CharField(default="start", max_length=225),
        ),
        migrations.AlterField(
            model_name="game",
            name="nine",
            field=models.CharField(default="start", max_length=225),
        ),
        migrations.AlterField(
            model_name="game",
            name="one",
            field=models.CharField(default="start", max_length=225),
        ),
        migrations.AlterField(
            model_name="game",
            name="seven",
            field=models.CharField(default="start", max_length=225),
        ),
        migrations.AlterField(
            model_name="game",
            name="six",
            field=models.CharField(default="start", max_length=225),
        ),
        migrations.AlterField(
            model_name="game",
            name="three",
            field=models.CharField(default="start", max_length=225),
        ),
        migrations.AlterField(
            model_name="game",
            name="two",
            field=models.CharField(default="start", max_length=225),
        ),
    ]
